### ISSUE TITLE
Images in issue detail not working

### ISSUE THREAD

**Issue by Rudoslav** [ekalinak/redmine-home#21]
![image](https://user-images.githubusercontent.com/10928828/36587137-78e37d72-1884-11e8-8b8a-a38e1c2722ca.png)

**Comment by ekalinak** [comment]
Actually this was fixed in b2ac8d5802ee7e5b0ef84657a2b44fb535952262 in both `master` and `menu-on-right-new` branches. 

Please update to latest version to see changes ...
