### ISSUE TITLE
resolved issues shown on homepage

### ISSUE THREAD

**Issue by tondax** [ekalinak/redmine-home#9]
Is it on purpose or could you omit such issues?

**Comment by ekalinak** [comment]
I checked [Redmine documentation for REST API](http://www.redmine.org/projects/redmine/wiki/Rest_Issues) and I found out, that there is possibility to return only tasks which are: 

* opened 
* closed 
* both _( opened, closed )_

no possibility to choose particular statuses. _( custom or not )_

However, I added possibility to show only "opened" statuses in "Redmine home application". You can find new configuration in **options section** _( Yes / No  attribute )_

---

**New idea**
After retrieving items from Redmine system, we can save locally only those task, which have configured statuses. 

_... issue continues :slightly_smiling_face:  ..._

**Comment by ekalinak** [comment]
New feature introduced in [58756b86](https://github.com/ekalinak/redmine-home/commit/758756b865e392a8dee5be7e19fd9acf6f7a76b1) replaced with possibility to choose, which statuses should not be visible in Redmine home.
